# This file is used to build the docker image and run the container.
services:
    mobyspulse:
        container_name: mobyspulse
        environment:
            - BASIC_AUTH_USERNAME=moby
            - BASIC_AUTH_PASSWORD=pulse
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "3000:3000"
        restart: unless-stopped
        build:
            context: .
        develop:
            watch:
                - action: rebuild
                  path: .